name: npm-publish
on:
  push:
    branches:
      - main
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master
      # Update package version and set up git
      - uses: actions/setup-node@master
      - name: Update package version and setup git
        run: |
          git config user.name "AngelMaCa"
          git config user.email angel.mani@eon.com.mx
          npm version 8.1.$(date +%s)
      # Publish to GitHub Package Registry
      - uses: actions/setup-node@master
        with:
          node-version: 14.0.0
          registry-url: https://npm.pkg.github.com/
          scope: 'AngelMaCa'
      - name: Publish to GitHub Package Registry
        run: npm install && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
